//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string StuNumber { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Tel { get; set; }
        public string TrueName { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int Status { get; set; }
    }
}
